### ISSUE TITLE
代码初始化的问题

### ISSUE THREAD

**Issue by phpmaple** [sunnyxx/XXNibBridge#1]
看例子是从xib中直接加载，如何让代码也可以。
如何初始化，下面这样好像不行
 XXDogeView *dogView = [XXDogeView xx_loadFromNib];
 dogView.frame = CGRectMake(30, 100, 100, 100);
  [self.view addSubview:aa];

**Comment by youngsing** [comment]
加一句dogView.translatesAutoresizingMaskIntoConstraints = YES;就行了
或者直接对dogView添加约束

**Comment by sunnyxx** [comment]
在IB中初始化的view默认translatesAutoresizingMaskIntoConstraints是NO，所以外部有需要的话需要手动开启。
