### ISSUE TITLE
关于判断当前 view 是 placeholder 的条件

### ISSUE THREAD

**Issue by BB9z** [sunnyxx/XXNibBridge#11]
2.2 后，一个 view 的 subviews 为空则认为是 placeholder。

这个判定我觉得不太合理，为了便于维护我在一些 placeholder 视图里放了一个 label 用来标明这块是什么，而且这样也要求实际 load 的视图必需有子视图。

从灵活性的角度，我可能会通过添加一个属性决定某个 view 是否需要被替换。更近一步的甚至可以再增加一个属性决定加载多个版本中的某一个，这样就很强大了。

**Comment by 949478479** [comment]
貌似在 IB 里为自定义的属性设值的时机发生在替换之后,面板自带属性设值是有效的,应该也只能靠特定 tag 值来判断了吧.

**Comment by BB9z** [comment]
试了试，没想到自定义属性设置的时间那么往后，accessibility 属性也是，而且从 decoder 中也获取不到任何信息…… 这样的话没想法了……
