### ISSUE TITLE
2.2.1版本似乎有点问题

### ISSUE THREAD

**Issue by wonderffee** [sunnyxx/XXNibBridge#12]
今天更新了Podfile，update后运行自己的app发现有一部自定义view显示不出来，各种定位发现update时这个库也进行了更新，从2.1版本更新到了2.2.1版本，然后加断点发现下面的代码不会被调用到，是修改了什么吗？
- (BOOL)xx_shouldApplyNibBridging {
  return YES;
  }

重新设置为2.1版本就正常了

**Comment by wonderffee** [comment]
搜了一下，好像最新版没有xx_shouldApplyNibBridging这个方法了，但是博文好像没有修改

**Comment by sunnyxx** [comment]
恩对，这个方法上个版本就标记废弃，这个版本被干掉了- -，还是以 README 为准哈~
