### ISSUE TITLE
视图与要嵌套的Controller相同前缀造成闪退

### ISSUE THREAD

**Issue by zj159963** [sunnyxx/XXNibBridge#13]
下载了一份demo，在测试的时候出现了这样一个问题，大致的情况是这样：
1、自定义一个视图叫做 XXView；
2、关联的Xib文件叫做XXView.xib；
3、在storyboard中添加XXView作为placeholder，一起正常，没有问题；
但是出现了一个这样的情况：
4、由于一些其他原因，测试一下navigationController，于是， 选中ViewController， embed in NavigationController， 新建一个controller， 名字叫做XXViewController，并没有使用storyboard；
5、在viewController中push这个XXViewController的时候， 闪退， 报错如下：
-[UIViewController _loadViewFromNibNamed:bundle:] loaded the "XXView" nib but the view outlet was not set.'
猜测是因为XXView和 XXViewController拥有同样的前缀造成，于是将其改为SBViewController， 一切正常。

**Comment by sunnyxx** [comment]
我感觉和前缀没关系，新建的 XXViewController 有个 XXView 的 IBOutlet 没清理干净吧？
