### ISSUE TITLE
Xib没有子控件时死循环

### ISSUE THREAD

**Issue by maplelover** [sunnyxx/XXNibBridge#16]
请问如果Xib没有子控件的话，有没办法解决死循环问题

重现步骤：
XXDogeView.xib删除所ImageView and Label

**Comment by lzwjava** [comment]
+1

堆栈：

![image](https://cloud.githubusercontent.com/assets/5022872/14063315/726096ae-f380-11e5-91f7-5dd6be495f5e.png)

问题在

``` objc
- (id)hackedAwakeAfterUsingCoder:(NSCoder *)decoder {
    if ([self.class conformsToProtocol:@protocol(XXNibBridge)] && ((UIView *)self).subviews.count == 0) {
        // "self" is placeholder view for this moment, replace it.
        return [XXNibBridgeImplementation instantiateRealViewFromPlaceholder:(UIView *)self];
    }
    return self;
}
```

通过 subviews.count 来区分出是 placeholderView 还是 realview。

当 realview 也没有 subviews 的时候，就一直调用循环了。

想到一个方法。对没有 subview 的 realview 一个 Tag，比如 123。对 tag 是 123 的View直接返回 self。

@sunnyxx

**Comment by sunnyxx** [comment]
为了代码的简洁采用的这个判断方式，因为基本上不会去 bridge 一个啥都没有的 xib，workaround: 把空 view 上面垫一个透明 view 让 subviews 的判断通过。

**Comment by lzwjava** [comment]
👍
