### ISSUE TITLE
有可能支持 Designable 么?

### ISSUE THREAD

**Issue by lexrus** [sunnyxx/XXNibBridge#3]
在 prepareForInterfaceBuilder 方法里把 xib 加载进来实现预览，有可能吗？

**Comment by sunnyxx** [comment]
这个提议不错，我去试试

**Comment by GF-Huang** [comment]
ViewController 释放时会崩溃.
**\* -[CustomView<XXNibBridge> release]: message sent to deallocated instance 0x79c14b50
发现是这个问题.

**Comment by GreatFireWall** [comment]
*** -[view<XXNibBridge> release]: message sent to deallocated instance 0x79c14b50
发现是这个问题.

**Comment by sunnyxx** [comment]
@GreatFireWall 这个问题请看 https://github.com/sunnyxx/XXNibBridge/issues/5
