### ISSUE TITLE
release时可能引起的crash

### ISSUE THREAD

**Issue by sunnyxx** [sunnyxx/XXNibBridge#5]
这是ARC下self的归属权问题导致的，已经修复了，可以删除pod中的文件，重新install一下（因为我没打新版本号，还是2.0，所以最好不要加--no-repo-update）

**Comment by sunnyxx** [comment]
我最近也进行了很多自测，发现一些潜在的问题，将在2.1这个新版本号里面修复（原谅我跳过了1.x的版本号- -）

**Comment by GF-Huang** [comment]
:+1:
