### ISSUE TITLE
view无法dealloc

### ISSUE THREAD

**Issue by victorxiong** [sunnyxx/XXNibBridge#6]
我发现只要引入你的2.0 库view就无法 dealloc
而替换成之前1.0的可以，麻烦看下是什么问题
很喜欢你写的这个，谢谢

**Comment by BB9z** [comment]
@sunnyxx 

'ns_consumes_self' attribute only applies to methods

应该是迁移到 2.0 时用 block 生成 IMP 导致内存管理标记失效了

**Comment by sunnyxx** [comment]
恩，这个问题我也发现了，还有awakeFromNib会被placeholder多调用一次的问题，准备不用block版本的imp了（ARC在block这块的attribute不生效，也是Apple需要修复的东西），在2.1版本会修复哈，这几天请共同关注下~

**Comment by sunnyxx** [comment]
2.1版本已修复
