### ISSUE TITLE
IBOutlet NSLayoutConstraint 链接宽高的约束会出错

### ISSUE THREAD

**Issue by victorxiong** [sunnyxx/XXNibBridge#8]
@property (nonatomic,weak) IBOutlet NSLayoutConstraint *layout;
链接宽高的约束会出错
请问是什么原因？

**Comment by ftxbird** [comment]
https://github.com/ylovern/XXNibBridge

**Comment by sunnyxx** [comment]
最新版本已经修复，谢谢
