### ISSUE TITLE
想要动态改变View的宽高约束，将宽高用IBOutlet引出，会crash

### ISSUE THREAD

**Issue by yangfeiyu** [sunnyxx/XXNibBridge#9]
引出的约束为nil，其他约束不会，求解决这个问题。

**Comment by ftxbird** [comment]
https://github.com/ylovern/XXNibBridge

**Comment by sunnyxx** [comment]
在要 Bridge 的 View 外层套一个 Wrapper View，把宽高约束设置到 Wrapper 上，再 IBOutlet 出去
